import type { Metadata } from 'next'
import { JetBrains_Mono } from 'next/font/google'
import ClientLayer from '@/wrappers/layer-client_support'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.className} antialiased`}>
        <ClientLayer>{children}</ClientLayer>
      </body>
    </html>
  )
}
